### ISSUE TITLE
source for modified sqlite3 

### ISSUE THREAD

**Issue by tinku99** [IsNull/ahkDBA#15]
could you please post source for modified sqlite3 (64bit) ? 
maybe as a separate repo... 

I assume you are using System.Data.SQLite...
I dropped in the official download from System.Data.Sqlite.dll and renamed it to sqlite3.dll in the x64 folder.
select query works fine, but insertmany fails...  (script works fine with 32 bit)

**Comment by ManiacDC** [comment]
I'm curious about this too.

**Comment by IsNull** [comment]
Hi there,

Firstly I am very glad that you are interested in contributing to this library. As you might be aware, I am no longer active in the AHK community nor do I use AHK myself anymore.

I am happy thought to accept further pull requests from you or anyone else.

About the dlls, I really can not remember much about it. Maybe you find some information in my old threads about it. However, I don't think I was using .NET Dlls but the plain C/C++ libraries.

Oh how fast time passes :-)

**Comment by ManiacDC** [comment]
Thanks! I was not aware.

OK, thanks. Do you happen to remember what compile switches you used for sqlite3?

**Comment by IsNull** [comment]
As far as I can remember, I used the official 32 bit dll. Since AHK was then moved to 64bit, 32 bit dlls could not longer be used, thus I needed a 64 bit version of it.

I think there was a website which offered a binary 64bit build and I used this. I really don't think I built it myself back then...

**Comment by ManiacDC** [comment]
I see, thanks! One of these days I'll take a crack at updating again. I dropped in the new 32 bit dll and things just plain didn't work. I'll have to find out why.

**Comment by ManiacDC** [comment]
I dropped the newest pre-compiled dll's into my program and it's working (the functionality I use, anyway).
