### ISSUE TITLE
getColumnNames in mysql returns empty.

### ISSUE THREAD

**Issue by patrickwreis** [IsNull/ahkDBA#18]
In your example, and in my tests getColumnNames returns empty.

**Comment by IsNull** [comment]
Thanks for your issue report, but I am no longer maintaining this repo since I switched away from AHK 4 years ago. 

If you send a pull request I will merge it in, and if you or someone else wants to take over the repo Im happy to transfer the ownership of it.

**Comment by IsNull** [comment]
fixed by PR #19 thank you @patrickwreis !
